FROM node:20-alpine AS build
WORKDIR /app
COPY admin-web/package*.json ./
RUN npm i
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
COPY admin-web ./
RUN npm run build
FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app ./
EXPOSE 3001
CMD ["npm","start","--","-p","3001"]
